

```{r}
library(sf)

baseMap=read_sf("selecDisMap.gpkg")
probables=read_sf("MostLikelyZG.gpkg")
grises=read_sf("selecDisMap.gpkg")
grises=grises[grises$Zona=='ZG' & grises$SpotsNBI=='3 coldSpot',]


```


```{r}
library(leaflet)

CENTER_of_MAP="function(btn, map){map.setView([-10, -75], 6)}" #ltln


baseLayer=leaflet()%>%
             addProviderTiles("CartoDB.Positron")

demoPlot=baseLayer %>% 
          addPolygons(data=probables,
                      label = ~provDist,
                      weight = 0.5, #border thickness
                      color = "red",#border color
                      group = "probables",
                      fillOpacity = 0.4) %>%
            addPolygons(data= grises,
                        label = ~provDist,
                      weight = 0.5, #border thickness
                      color = "silver",#border color
                      group = "grises",
                      fillOpacity = 0.4) %>% 
  addLayersControl(
    overlayGroups = c("probables", "grises"),
    options = layersControlOptions(collapsed = FALSE)
  )%>% hideGroup("probables")%>% 

    # adding the button
    addEasyButton(
        easyButton(icon="fa-home", # a symbol
                   title="Zoom to Level 1",
                   onClick=JS(CENTER_of_MAP)))
demoPlot

```

